"""propopic again

Revision ID: 1b42b56fd5cb
Revises: 49a4a02ccd5b
Create Date: 2017-12-11 16:28:21.985500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b42b56fd5cb'
down_revision = '49a4a02ccd5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'users', ['pro_pic'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###
