"""no propic

Revision ID: 49a4a02ccd5b
Revises: a0a724392c4c
Create Date: 2017-12-10 21:03:34.453189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49a4a02ccd5b'
down_revision = 'a0a724392c4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pro_pic_key', 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_pro_pic_key', 'users', ['pro_pic'])
    # ### end Alembic commands ###
