"""no propic

Revision ID: 997647e3ee38
Revises: 1b42b56fd5cb
Create Date: 2017-12-11 16:44:31.391160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '997647e3ee38'
down_revision = '1b42b56fd5cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pro_pic_key', 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_pro_pic_key', 'users', ['pro_pic'])
    # ### end Alembic commands ###
