"""propipic

Revision ID: a0a724392c4c
Revises: d0ec7900d7ca
Create Date: 2017-12-10 20:33:39.480178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a724392c4c'
down_revision = 'd0ec7900d7ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', sa.LargeBinary(), nullable=True))
    op.create_unique_constraint(None, 'users', ['pro_pic'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###
