"""checking

Revision ID: d0ec7900d7ca
Revises: e34714bcde55
Create Date: 2017-12-10 18:40:20.833257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0ec7900d7ca'
down_revision = 'e34714bcde55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_list', sa.Column('restaurant_id', sa.Integer(), nullable=True))
    op.drop_constraint('personal_list_user_id_fkey', 'personal_list', type_='foreignkey')
    op.create_foreign_key(None, 'personal_list', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_column('personal_list', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal_list', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'personal_list', type_='foreignkey')
    op.create_foreign_key('personal_list_user_id_fkey', 'personal_list', 'restaurants', ['user_id'], ['id'])
    op.drop_column('personal_list', 'restaurant_id')
    # ### end Alembic commands ###
