"""no pro pic

Revision ID: e34714bcde55
Revises: 
Create Date: 2017-12-09 16:03:05.279611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e34714bcde55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pro_pic_key', 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_pro_pic_key', 'users', ['pro_pic'])
    # ### end Alembic commands ###
